### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by Cysime** [Clem-Fern/rtabby-web-api#14]
Hi,

Thanks for this implement of sync API for Tabby.
I found that this project is not ARM64 ready by default, but it's quite easy to add the ARM64 support.

All we need to do is clone the project, uncomment the build section in `docer-compose` file, and modify the Dockerfile, change `x86_64 `into `aarch64`, and it runs smoothly without any issue.

```
# syntax=docker/dockerfile:1
FROM rust:1.73-alpine AS builder
WORKDIR /build
COPY . .
RUN apk add --no-cache build-base && \
    cargo build --target=aarch64-unknown-linux-musl --release --no-default-features -F sqlite-bundle

FROM scratch

WORKDIR /config

COPY --from=builder /build/target/aarch64-unknown-linux-musl/release/rtabby-web-api /
COPY --from=builder /build/users.exemple.yml .

CMD ["/rtabby-web-api"]
```

**Comment by Clem-Fern** [comment]
Hey,

Could be great to have arm platform directly available in the package registry. I will try to add this in the current build workflow :)

**Comment by Clem-Fern** [comment]
Hi @Cysime,

I added arm64 platform in CI. Build in progress.
Could you please make me a feedback ? I don't have any arm device to test :/

**Comment by bigwave** [comment]
Works for me on Raspberry Pi 4 Model B Rev 1.5

**Comment by Clem-Fern** [comment]
> Works for me on Raspberry Pi 4 Model B Rev 1.5

@bigwave Thank's for the feedback
