### ISSUE TITLE
New release is not marked as latest in ghcr

### ISSUE THREAD

**Issue by M1Screw** [Clem-Fern/rtabby-web-api#24]
Maybe this has something to do with recent changes to build systems/github actions?

![image](https://github.com/Clem-Fern/rtabby-web-api/assets/14369594/1ad72f07-b0c9-4b87-aac8-1ba3f8ca1f7f)

**Comment by Clem-Fern** [comment]
Hey @M1Screw 

Latest release workflow have failed. I will try to fix it asap.

**Comment by Clem-Fern** [comment]
Workflow fixed. It should be alright now.
