### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by tiagocasalribeiro** [Clem-Fern/rtabby-web-api#4]
I am able to deploy on a debian 12 machine running docker following your instructions but the web page spits a 401 error message and I am unable to connect to it

**Comment by Clem-Fern** [comment]
Hey @tiagocasalribeiro,

Sorry to hear that. Just to be sure, you've got an 401 error when trying through your web browser or on Settings > Config Sync Tabby's tab ?

This service is not supposed to be used through a browser. You have to create your user in `users.yml` file and then directly configure your url and token in Tabby.

**Comment by tiagocasalribeiro** [comment]
I ended up figuring it out... when I pasted the tokenI just got a spinning sign, but changing to another tab and back to the sync tab, confirmed the config and it works now. thanks and keep up the good work
