### ISSUE TITLE
[Feature Request]SQLite support

### ISSUE THREAD

**Issue by EkkoG** [Clem-Fern/rtabby-web-api#6]
Please add SQLite support, it's more convince when self-use. I see diesel has build-in SQLite support, and if the api does not use dedicate feature of MySQL, is it possible to add sqlite feature of diesel? https://github.com/Clem-Fern/rtabby-web-api/blob/ec8c429cdcd58f152cc86a0a54d8a76b5fcd595e/Cargo.toml#L22C14-L22C14

**Comment by Clem-Fern** [comment]
Yeah, it was initially using sqlite instead of mysql when I first created this. It shouldnt be that hard to add sqlite again.

**Comment by Clem-Fern** [comment]
Hey @EkkoG,
I just published a new version which support sqlite.

https://github.com/Clem-Fern/rtabby-web-api#getting-started-sqlite
https://github.com/Clem-Fern/rtabby-web-api#usage-sqlite

**Comment by EkkoG** [comment]
Thanks for your great work!

I have successfully run the SQLite version and it works fine.

I think the documentation should make it clearer that user token is used as secret sync token.

And for now, I guess the token only can be add manually, can we add a method to allow user to create the token by themself? Maybe it better add an auth method like Google login, and return a token after login, or integrated OpenID, both of the solution needs a frontend page to let user input something.

**Comment by Clem-Fern** [comment]
> I think the documentation should make it clearer that user token is used as secret sync token.

I will update the readme then, thank's
