### ISSUE TITLE
[Feature Request] Allow user create token by themself

### ISSUE THREAD

**Issue by EkkoG** [Clem-Fern/rtabby-web-api#9]
As https://github.com/Clem-Fern/rtabby-web-api/issues/6#issuecomment-1846490054 say, for now user can not create a token by themself

Add route `/login`, return a simple a tag page, click the a tag will open a GitHub auth URL with client_id https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#redirect-urls
Add route `/loigin_redirect` to receive the callback of URL from GitHub with code, after server receive the request, it can get a GitHub access token with the code https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#2-users-are-redirected-back-to-your-site-by-github

Get GitHub user id with the access token, create a user and return the user token.

I try to add a route at user.rs, it will protect by the auth system, I'm not familiar with Rust and Actix-Web, so for now I need to learn many things to imp the idea.

**Comment by EkkoG** [comment]
I have created a PR implement both of the two auth method. Please review my pull request when you have time.

**Comment by Clem-Fern** [comment]
Hey @EkkoG,

I finally got the time to merge this feature. I reworked it a bit to only publish login endpoint when oauth provider is configured.

Thank's again for your work ;)
